# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CokePods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CokePods
pod 'Alamofire', '~> 5.0.0-rc.1'

  target 'CokePodsTests' do
    inherit! :search_paths
    # Pods for testing
pod 'Alamofire', '~> 5.0.0-rc.1'
  end

end
